name: Main service CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: yarn install --frozen-lockfile
            - run: yarn lint
    playwright:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - uses: microsoft/playwright-github-action@v1
            - name: Install dependencies
              run: yarn install --frozen-lockfile && npx playwright install
            - name: Run tests
              run: yarn playwright:ci
