name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Lint codebase
              run: yarn lint
    check-types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Check type validity
              run: yarn tsc --noEmit
    playwright-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "yarn"
            # - uses: actions/cache@v2
            #   with:
            #       path: ${{ github.workspace }}/.next/cache
            #       # Generate a new cache whenever packages or source files change.
            #       key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
            #       # If source files changed but packages didn't, rebuild from a prior cache.
            #       restore-keys: |
            #           ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            - name: Install dependencies
              run: yarn install --frozen-lockfile && npx playwright install
            - name: Run playwright tests
              run: yarn playwright:ci
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run unit tests
              run: yarn test
